create policy "Users insert own error log" on public.admin_error_log for insert to authenticated with check (((user_id = auth.uid()) OR (user_id IS NULL)));
create policy "admin read notif" on public.admin_notifications for select to authenticated using (has_role(auth.uid(), 'admin'::app_role));
create policy "admin update notif" on public.admin_notifications for update to authenticated using (has_role(auth.uid(), 'admin'::app_role)) with check (has_role(auth.uid(), 'admin'::app_role));
create policy "evals_own" on public.agent_evals for all to authenticated, anon using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "golden_read_auth" on public.agent_golden_dataset for select to authenticated using (true);
create policy "admins manage incidents" on public.agent_incidents for all to authenticated using (has_role(auth.uid(), 'admin'::app_role)) with check (has_role(auth.uid(), 'admin'::app_role));
create policy "own agent memory delete" on public.agent_memory_files for delete to authenticated using ((auth.uid() = user_id));
create policy "own agent memory read" on public.agent_memory_files for select to authenticated using ((auth.uid() = user_id));
create policy "own agent memory update" on public.agent_memory_files for update to authenticated using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "own agent memory write" on public.agent_memory_files for insert to authenticated with check ((auth.uid() = user_id));
create policy "agent_messages_owner_all" on public.agent_messages for all to authenticated using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "admins view obs" on public.agent_observations for select to authenticated using (has_role(auth.uid(), 'admin'::app_role));
create policy "admins manage proposals" on public.agent_proposals for all to authenticated using (has_role(auth.uid(), 'admin'::app_role)) with check (has_role(auth.uid(), 'admin'::app_role));
create policy "admins view runs" on public.agent_runs for select to authenticated using (has_role(auth.uid(), 'admin'::app_role));
create policy "agent_sessions_owner_all" on public.agent_sessions for all to authenticated using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "Users manage own bindings" on public.agent_tool_bindings for all to authenticated using ((user_id = auth.uid())) with check ((user_id = auth.uid()));
create policy "Users view own invocations" on public.agent_tool_invocations for select to authenticated using ((user_id = auth.uid()));
create policy "Anyone authenticated can read active tools" on public.agent_tools_registry for select to authenticated using ((is_active = true));
create policy "traces_own" on public.agent_traces for all to authenticated, anon using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "admins manage agents" on public.ai_agents for all to authenticated using (has_role(auth.uid(), 'admin'::app_role)) with check (has_role(auth.uid(), 'admin'::app_role));
create policy "authenticated read agents" on public.ai_agents for select to authenticated using (true);
create policy "Users can insert own personalization" on public.ai_personalization for insert to authenticated with check ((auth.uid() = user_id));
create policy "Users can update own personalization" on public.ai_personalization for update to authenticated using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "Users can view own personalization" on public.ai_personalization for select to authenticated using ((auth.uid() = user_id));
create policy "ai_project_files_own" on public.ai_project_files for all to authenticated using ((EXISTS ( SELECT 1) with check (ects p);
create policy "ai_project_messages_own" on public.ai_project_messages for all to authenticated using ((EXISTS ( SELECT 1) with check (ects p);
create policy "ai_project_snapshots_own" on public.ai_project_snapshots for all to authenticated using ((EXISTS ( SELECT 1) with check (ects p);
create policy "usage_insert_owner" on public.ai_project_usage for insert to authenticated, anon with check ((EXISTS ( SELECT 1);
create policy "usage_select_owner" on public.ai_project_usage for select to authenticated, anon using ((EXISTS ( SELECT 1) with check (ects p);
create policy "Admins manage alibaba_keys" on public.alibaba_keys for all to authenticated using (has_role(auth.uid(), 'admin'::app_role)) with check (has_role(auth.uid(), 'admin'::app_role));
create policy "Anyone can insert anonymous usage" on public.anonymous_chat_usage for insert to anon,authenticated with check ((auth.role() = ANY (ARRAY['anon'::text, 'authenticated'::text])));
create policy "Admins manage apify_keys" on public.apify_keys for all to authenticated using (has_role(auth.uid(), 'admin'::app_role)) with check (has_role(auth.uid(), 'admin'::app_role));
create policy "app_kv_owner_delete" on public.app_kv for delete to authenticated, anon using ((auth.uid() = user_id));
create policy "app_kv_owner_insert" on public.app_kv for insert to authenticated, anon with check ((auth.uid() = user_id));
create policy "app_kv_owner_select" on public.app_kv for select to authenticated, anon using ((auth.uid() = user_id));
create policy "app_kv_owner_update" on public.app_kv for update to authenticated, anon using ((auth.uid() = user_id));
create policy "Users read own licenses" on public.appsumo_licenses for select to authenticated using ((auth.uid() = user_id));
create policy "users delete own chunks" on public.attachment_chunks for delete to authenticated, anon using ((auth.uid() = user_id));
create policy "users insert own chunks" on public.attachment_chunks for insert to authenticated, anon with check ((auth.uid() = user_id));
create policy "users view own chunks" on public.attachment_chunks for select to authenticated, anon using ((auth.uid() = user_id));
create policy "users delete own background jobs" on public.background_jobs for delete to authenticated, anon using ((auth.uid() = user_id));
create policy "users insert own background jobs" on public.background_jobs for insert to authenticated, anon with check ((auth.uid() = user_id));
create policy "users read own background jobs" on public.background_jobs for select to authenticated, anon using ((auth.uid() = user_id));
create policy "users update own background jobs" on public.background_jobs for update to authenticated, anon using ((auth.uid() = user_id));
create policy "admins read audit log" on public.billing_audit_log for select to authenticated, anon using (has_role(auth.uid(), 'admin'::app_role));
create policy "Anyone can read active skus" on public.billing_skus for select to authenticated, anon using ((active = true));
create policy "admins manage cats" on public.blog_categories for all to authenticated using (has_role(auth.uid(), 'admin'::app_role)) with check (has_role(auth.uid(), 'admin'::app_role));
create policy "auth read cats" on public.blog_categories for select to authenticated using (true);
create policy "public read cats" on public.blog_categories for select to anon using (true);
create policy "admins manage posts" on public.blog_posts for all to authenticated using (has_role(auth.uid(), 'admin'::app_role)) with check (has_role(auth.uid(), 'admin'::app_role));
create policy "auth read published posts" on public.blog_posts for select to authenticated using (((status = 'published'::text) OR has_role(auth.uid(), 'admin'::app_role)));
create policy "public read published posts" on public.blog_posts for select to anon using ((status = 'published'::text));
create policy "topic_queue_admin_read" on public.blog_topic_queue for select to authenticated using (has_role(auth.uid(), 'admin'::app_role));
create policy "topic_queue_admin_write" on public.blog_topic_queue for insert to authenticated with check (has_role(auth.uid(), 'admin'::app_role));
create policy "Users can manage own books" on public.books for all to authenticated using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "Admins manage brave_keys" on public.brave_keys for all to authenticated using (has_role(auth.uid(), 'admin'::app_role)) with check (has_role(auth.uid(), 'admin'::app_role));
create policy "Users can manage own calendar connections" on public.calendar_connections for all to authenticated using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "Users insert own citations" on public.chat_citations for insert to authenticated with check ((auth.uid() = user_id));
create policy "Users view own citations" on public.chat_citations for select to authenticated using ((auth.uid() = user_id));
create policy "Users insert own followups" on public.chat_followups for insert to authenticated with check ((auth.uid() = user_id));
create policy "Users view own followups" on public.chat_followups for select to authenticated using ((auth.uid() = user_id));
create policy "users insert own interaction events" on public.chat_interaction_events for insert to authenticated with check ((auth.uid() = user_id));
create policy "users read own interaction events" on public.chat_interaction_events for select to authenticated using ((auth.uid() = user_id));
create policy "admins manage chat_models" on public.chat_models for all to authenticated using (has_role(auth.uid(), 'admin'::app_role)) with check (has_role(auth.uid(), 'admin'::app_role));
create policy "chat_models readable by all" on public.chat_models for select to authenticated, anon using (true);
create policy "Users view own router logs" on public.chat_router_logs for select to authenticated using ((auth.uid() = user_id));
create policy "Users delete their own stream buffers" on public.chat_stream_buffers for delete to authenticated, anon using ((auth.uid() = user_id));
create policy "Users insert their own stream buffers" on public.chat_stream_buffers for insert to authenticated, anon with check ((auth.uid() = user_id));
create policy "Users read their own stream buffers" on public.chat_stream_buffers for select to authenticated, anon using ((auth.uid() = user_id));
create policy "Users update their own stream buffers" on public.chat_stream_buffers for update to authenticated, anon using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "service_role_only_select" on public.composio_auth_configs for select to service_role using (true);
create policy "users_view_own_connections" on public.composio_connections for select to authenticated using ((auth.uid() = user_id));
create policy "Anyone can submit contact form" on public.contact_submissions for insert to anon,authenticated with check ((auth.role() = ANY (ARRAY['anon'::text, 'authenticated'::text])));
create policy "Invited user can view own invites" on public.conversation_invites for select to authenticated using (is_invite_for_current_user(invite_email));
create policy "Owner can manage invites" on public.conversation_invites for all to authenticated using (owns_conversation(conversation_id)) with check (owns_conversation(conversation_id));
create policy "Members can view conversation members" on public.conversation_members for select to authenticated using (is_conversation_member(conversation_id, auth.uid()));
create policy "Owner can delete members" on public.conversation_members for delete to authenticated using (owns_conversation(conversation_id));
create policy "Owner can insert members" on public.conversation_members for insert to authenticated with check (owns_conversation(conversation_id));
create policy "Users can delete own conversation summaries" on public.conversation_summaries for delete to authenticated using ((auth.uid() = user_id));
create policy "Users can insert own conversation summaries" on public.conversation_summaries for insert to authenticated with check (((auth.uid() = user_id) AND owns_conversation(conversation_id)));
create policy "Users can update own conversation summaries" on public.conversation_summaries for update to authenticated using ((auth.uid() = user_id)) with check (((auth.uid() = user_id) AND owns_conversation(conversation_id)));
create policy "Users can view own conversation summaries" on public.conversation_summaries for select to authenticated using ((auth.uid() = user_id));
create policy "Public can view shared conversations" on public.conversations for select to anon,authenticated using (((is_shared = true) AND (share_id IS NOT NULL)));
create policy "Users can manage own conversations" on public.conversations for all to authenticated using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "Workspace members can update conversations" on public.conversations for update to authenticated, anon using (((workspace_id IS NOT NULL) AND is_workspace_member(workspace_id, auth.uid())));
create policy "Workspace members can view conversations" on public.conversations for select to authenticated, anon using (((workspace_id IS NOT NULL) AND is_workspace_member(workspace_id, auth.uid())));
create policy "Service role writes credit transactions" on public.credit_transactions for insert to authenticated, anon with check (((auth.jwt() ->> 'role'::text) = 'service_role'::text));
create policy "Users can view own transactions" on public.credit_transactions for select to authenticated, anon using ((auth.uid() = user_id));
create policy "Users read own credit transactions" on public.credit_transactions for select to authenticated, anon using ((auth.uid() = user_id));
create policy "Users read own daily usage" on public.daily_free_usage for select to authenticated using ((auth.uid() = user_id));
create policy "Anyone can read promo slots" on public.daily_promo_slots for select to authenticated, anon using (true);
create policy "Users view their own document premium usage" on public.document_premium_usage for select to authenticated, anon using ((auth.uid() = user_id));
create policy "Document template images are publicly readable" on public.document_template_images for select to authenticated, anon using (true);
create policy "Document templates are publicly readable" on public.document_templates for select to authenticated, anon using (true);
create policy "Anyone can read active dodo products" on public.dodo_products for select to authenticated, anon using ((active = true));
create policy "users_delete_own_executions" on public.e2b_executions for delete to authenticated, anon using ((auth.uid() = user_id));
create policy "users_insert_own_executions" on public.e2b_executions for insert to authenticated, anon with check ((auth.uid() = user_id));
create policy "users_select_own_executions" on public.e2b_executions for select to authenticated, anon using ((auth.uid() = user_id));
create policy "users_update_own_executions" on public.e2b_executions for update to authenticated, anon using ((auth.uid() = user_id));
create policy "Admins manage e2b keys" on public.e2b_keys for all to authenticated using (has_role(auth.uid(), 'admin'::app_role)) with check (has_role(auth.uid(), 'admin'::app_role));
create policy "edge_audit_log_own" on public.edge_audit_log for select to authenticated using (((auth.uid() = user_id) OR has_role(auth.uid(), 'admin'::app_role)));
create policy "edge_rate_limits_service_only_read" on public.edge_rate_limits for select to authenticated using (false);
create policy "Users can view own email logs" on public.email_logs for select to authenticated, anon using ((auth.uid() = user_id));
create policy "Users manage own focus sessions" on public.focus_sessions for all to authenticated using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "Users read their own free trial usage" on public.free_trial_usage for select to authenticated using ((auth.uid() = user_id));
create policy "Public can view shared sites" on public.generated_sites for select to anon,authenticated using ((is_public = true));
create policy "Users manage own sites" on public.generated_sites for all to authenticated using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "Users can manage own songs" on public.generated_songs for all to authenticated using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "Users can insert own jobs" on public.generation_jobs for insert to authenticated with check ((auth.uid() = user_id));
create policy "Users can view own jobs" on public.generation_jobs for select to authenticated using ((auth.uid() = user_id));
create policy "Anyone can view active headshot templates" on public.headshot_templates for select to anon,authenticated using ((is_active = true));
create policy "Users manage their own HITL approvals" on public.hitl_tool_approvals for all to authenticated, anon using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "Authenticated read sync runs" on public.i18n_sync_runs for select to authenticated using (true);
create policy "Public read translations" on public.i18n_translations for select to authenticated, anon using (true);
create policy "fal_image_models_read_anon" on public.image_models for select to anon using ((is_active = true));
create policy "fal_image_models_read_authenticated" on public.image_models for select to authenticated using ((is_active = true));
create policy "Anyone can view active templates" on public.image_templates for select to anon,authenticated using ((is_active = true));
create policy "Users can create their own kashier orders" on public.kashier_orders for insert to authenticated with check ((auth.uid() = user_id));
create policy "Users can view their own kashier orders" on public.kashier_orders for select to authenticated using ((auth.uid() = user_id));
create policy "admin read usage" on public.key_usage_log for select to authenticated using (has_role(auth.uid(), 'admin'::app_role));
create policy "Admins manage landing prompts" on public.landing_page_prompts for all to authenticated using (has_role(auth.uid(), 'admin'::app_role)) with check (has_role(auth.uid(), 'admin'::app_role));
create policy "Anyone can read published rows (non-prompt cols)" on public.landing_page_prompts for select to anon,authenticated using ((is_published = true));
create policy "learn_profile insert own" on public.learn_profile for insert to authenticated, anon with check ((auth.uid() = user_id));
create policy "learn_profile select own" on public.learn_profile for select to authenticated, anon using ((auth.uid() = user_id));
create policy "learn_profile update own" on public.learn_profile for update to authenticated, anon using ((auth.uid() = user_id));
create policy "learn_sessions insert own" on public.learn_sessions for insert to authenticated, anon with check ((auth.uid() = user_id));
create policy "learn_sessions select own" on public.learn_sessions for select to authenticated, anon using ((auth.uid() = user_id));
create policy "learn_sessions update own" on public.learn_sessions for update to authenticated, anon using ((auth.uid() = user_id));
create policy "admin manage manus keys" on public.manus_keys for all to authenticated using (has_role(auth.uid(), 'admin'::app_role)) with check (has_role(auth.uid(), 'admin'::app_role));
create policy "own accounts" on public.marketing_accounts for all to authenticated, anon using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "ads_delete_own" on public.marketing_ads for delete to authenticated using ((auth.uid() = user_id));
create policy "ads_insert_own" on public.marketing_ads for insert to authenticated with check ((auth.uid() = user_id));
create policy "ads_select_own" on public.marketing_ads for select to authenticated using ((auth.uid() = user_id));
create policy "ads_update_own" on public.marketing_ads for update to authenticated using ((auth.uid() = user_id));
create policy "analytics owner reads" on public.marketing_analytics for all to authenticated, anon using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "campaigns_delete_own" on public.marketing_campaigns for delete to authenticated using ((auth.uid() = user_id));
create policy "campaigns_insert_own" on public.marketing_campaigns for insert to authenticated with check ((auth.uid() = user_id));
create policy "campaigns_select_own" on public.marketing_campaigns for select to authenticated using ((auth.uid() = user_id));
create policy "campaigns_update_own" on public.marketing_campaigns for update to authenticated using ((auth.uid() = user_id));
create policy "own campaigns" on public.marketing_campaigns for all to authenticated, anon using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "limits owner manages" on public.marketing_platform_limits for all to authenticated, anon using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "own posts" on public.marketing_posts for all to authenticated, anon using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "own publish log" on public.marketing_publish_log for all to authenticated, anon using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "queue owner manages" on public.marketing_publish_queue for all to authenticated, anon using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "Users manage their own mcp connections" on public.mcp_connections for all to authenticated, anon using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "media_assets_delete_own" on public.media_assets for delete to authenticated using ((auth.uid() = user_id));
create policy "media_assets_insert_own" on public.media_assets for insert to authenticated with check ((auth.uid() = user_id));
create policy "media_assets_select_own" on public.media_assets for select to authenticated using ((auth.uid() = user_id));
create policy "media_assets_update_own" on public.media_assets for update to authenticated using ((auth.uid() = user_id));
create policy "admins read logs" on public.media_generation_log for select to authenticated using ((EXISTS ( SELECT 1) with check (admins ba);
create policy "admins manage limits" on public.media_key_limits for all to authenticated using ((EXISTS ( SELECT 1) with check (admins ba);
create policy "admins read usage" on public.media_key_usage for select to authenticated using ((EXISTS ( SELECT 1) with check (admins ba);
create policy "admin manage prompts" on public.media_page_prompts for all to authenticated using (has_role(auth.uid(), 'admin'::app_role)) with check (has_role(auth.uid(), 'admin'::app_role));
create policy "public read prompts" on public.media_page_prompts for select to anon,authenticated using (true);
create policy "Admins manage media_provider_keys" on public.media_provider_keys for all to authenticated using (has_role(auth.uid(), 'admin'::app_role)) with check (has_role(auth.uid(), 'admin'::app_role));
create policy "Users can view own recordings" on public.meeting_recordings for select to authenticated using ((auth.uid() = user_id));
create policy "Users can manage own meetings" on public.meetings for all to authenticated using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "own delete" on public.megsy_code_skills for delete to authenticated using ((auth.uid() = user_id));
create policy "own insert" on public.megsy_code_skills for insert to authenticated with check ((auth.uid() = user_id));
create policy "own select" on public.megsy_code_skills for select to authenticated using ((auth.uid() = user_id));
create policy "own update" on public.megsy_code_skills for update to authenticated using ((auth.uid() = user_id));
create policy "mf_own_delete" on public.message_feedback for delete to authenticated using ((auth.uid() = user_id));
create policy "mf_own_insert" on public.message_feedback for insert to authenticated with check ((auth.uid() = user_id));
create policy "mf_own_select" on public.message_feedback for select to authenticated using ((auth.uid() = user_id));
create policy "mf_own_update" on public.message_feedback for update to authenticated using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "Members can view reactions in their conversations" on public.message_reactions for select to authenticated, anon using (is_conversation_member(conversation_id, auth.uid()));
create policy "Users can add their own reactions" on public.message_reactions for insert to authenticated, anon with check (((auth.uid() = user_id) AND is_conversation_member(conversation_id, auth.uid())));
create policy "Users can delete their own reactions" on public.message_reactions for delete to authenticated, anon using ((auth.uid() = user_id));
create policy "Members can view reads in their conversations" on public.message_reads for select to authenticated, anon using (is_conversation_member(conversation_id, auth.uid()));
create policy "Users can delete their own read marks" on public.message_reads for delete to authenticated, anon using ((auth.uid() = user_id));
create policy "Users can mark messages as read for themselves" on public.message_reads for insert to authenticated, anon with check (((auth.uid() = user_id) AND is_conversation_member(conversation_id, auth.uid())));
create policy "Members can insert messages" on public.messages for insert to authenticated with check (is_conversation_member(conversation_id, auth.uid()));
create policy "Members can view conversation messages" on public.messages for select to authenticated using (is_conversation_member(conversation_id, auth.uid()));
create policy "Public can view messages of shared conversations" on public.messages for select to anon,authenticated using ((EXISTS ( SELECT 1) with check (ersations);
create policy "Users can manage own messages" on public.messages for all to authenticated using (owns_conversation(conversation_id)) with check (owns_conversation(conversation_id));
create policy "Anyone can view model media" on public.model_media for select to anon,authenticated using (true);
create policy "model_pricing_read_all_authenticated" on public.model_pricing for select to authenticated using (true);
create policy "model_pricing_read_anon" on public.model_pricing for select to anon using ((enabled = true));
create policy "Users can insert own preferences" on public.notification_preferences for insert to authenticated, anon with check ((auth.uid() = user_id));
create policy "Users can update own preferences" on public.notification_preferences for update to authenticated, anon using ((auth.uid() = user_id));
create policy "Users can view own preferences" on public.notification_preferences for select to authenticated, anon using ((auth.uid() = user_id));
create policy "Users can update own notifications" on public.notifications for update to authenticated, anon using ((auth.uid() = user_id));
create policy "Users can view own notifications" on public.notifications for select to authenticated, anon using ((auth.uid() = user_id));
create policy "Users insert own agent msgs" on public.operator_agent_messages for insert to authenticated, anon with check ((EXISTS ( SELECT 1);
create policy "Users view own agent msgs" on public.operator_agent_messages for select to authenticated, anon using ((EXISTS ( SELECT 1) with check (ator_runs r);
create policy "Users insert own artifacts" on public.operator_artifacts for insert to authenticated, anon with check ((EXISTS ( SELECT 1);
create policy "Users view own artifacts" on public.operator_artifacts for select to authenticated, anon using ((EXISTS ( SELECT 1) with check (ator_runs r);
create policy "Users view own audit log" on public.operator_audit_log for select to authenticated, anon using ((auth.uid() = user_id));
create policy "Users delete own dynamic agents" on public.operator_dynamic_agents for delete to authenticated, anon using ((auth.uid() = user_id));
create policy "Users insert own dynamic agents" on public.operator_dynamic_agents for insert to authenticated, anon with check ((auth.uid() = user_id));
create policy "Users update own dynamic agents" on public.operator_dynamic_agents for update to authenticated, anon using ((auth.uid() = user_id));
create policy "Users view own dynamic agents" on public.operator_dynamic_agents for select to authenticated, anon using ((auth.uid() = user_id));
create policy "Users delete own memory" on public.operator_memory for delete to authenticated, anon using ((auth.uid() = user_id));
create policy "Users insert own memory" on public.operator_memory for insert to authenticated, anon with check ((auth.uid() = user_id));
create policy "Users view own memory" on public.operator_memory for select to authenticated, anon using ((auth.uid() = user_id));
create policy "Users delete own runs" on public.operator_runs for delete to authenticated, anon using ((auth.uid() = user_id));
create policy "Users insert own runs" on public.operator_runs for insert to authenticated, anon with check ((auth.uid() = user_id));
create policy "Users update own runs" on public.operator_runs for update to authenticated, anon using ((auth.uid() = user_id));
create policy "Users view own runs" on public.operator_runs for select to authenticated, anon using ((auth.uid() = user_id));
create policy "Users insert own run steps" on public.operator_steps for insert to authenticated, anon with check ((EXISTS ( SELECT 1);
create policy "Users update own run steps" on public.operator_steps for update to authenticated, anon using ((EXISTS ( SELECT 1) with check (ator_runs r);
create policy "Users view own run steps" on public.operator_steps for select to authenticated, anon using ((EXISTS ( SELECT 1) with check (ator_runs r);
create policy "Users insert own operator settings" on public.operator_user_settings for insert to authenticated, anon with check ((auth.uid() = user_id));
create policy "Users update own operator settings" on public.operator_user_settings for update to authenticated, anon using ((auth.uid() = user_id));
create policy "Users view own operator settings" on public.operator_user_settings for select to authenticated, anon using ((auth.uid() = user_id));
create policy "Users delete own monitor events" on public.parallel_monitor_events for delete to authenticated using ((auth.uid() = user_id));
create policy "Users read own monitor events" on public.parallel_monitor_events for select to authenticated using ((auth.uid() = user_id));
create policy "Users update own monitor events" on public.parallel_monitor_events for update to authenticated using ((auth.uid() = user_id));
create policy "Users delete own monitors" on public.parallel_monitors for delete to authenticated using ((auth.uid() = user_id));
create policy "Users insert own monitors" on public.parallel_monitors for insert to authenticated with check ((auth.uid() = user_id));
create policy "Users read own monitors" on public.parallel_monitors for select to authenticated using ((auth.uid() = user_id));
create policy "Users update own monitors" on public.parallel_monitors for update to authenticated using ((auth.uid() = user_id));
create policy "Users delete own parallel tasks" on public.parallel_tasks for delete to authenticated using ((auth.uid() = user_id));
create policy "Users insert own parallel tasks" on public.parallel_tasks for insert to authenticated with check ((auth.uid() = user_id));
create policy "Users read own parallel tasks" on public.parallel_tasks for select to authenticated using ((auth.uid() = user_id));
create policy "Users update own parallel tasks" on public.parallel_tasks for update to authenticated using ((auth.uid() = user_id));
create policy "Service role manages payment events" on public.payment_events for all to authenticated, anon using (((auth.jwt() ->> 'role'::text) = 'service_role'::text)) with check (((auth.jwt() ->> 'role'::text) = 'service_role'::text));
create policy "Users view their own payment events" on public.payment_events for select to authenticated, anon using ((auth.uid() = user_id));
create policy "users read own video jobs" on public.pending_video_jobs for select to authenticated using ((auth.uid() = user_id));
create policy "Users delete own pipedream accounts" on public.pipedream_accounts for delete to authenticated, anon using ((auth.uid() = user_id));
create policy "Users insert own pipedream accounts" on public.pipedream_accounts for insert to authenticated, anon with check ((auth.uid() = user_id));
create policy "Users update own pipedream accounts" on public.pipedream_accounts for update to authenticated, anon using ((auth.uid() = user_id));
create policy "Users view own pipedream accounts" on public.pipedream_accounts for select to authenticated, anon using ((auth.uid() = user_id));
create policy "users_delete_own_tool_settings" on public.pipedream_tool_settings for delete to authenticated using ((auth.uid() = user_id));
create policy "users_insert_own_tool_settings" on public.pipedream_tool_settings for insert to authenticated with check ((auth.uid() = user_id));
create policy "users_select_own_tool_settings" on public.pipedream_tool_settings for select to authenticated using ((auth.uid() = user_id));
create policy "users_update_own_tool_settings" on public.pipedream_tool_settings for update to authenticated using ((auth.uid() = user_id));
create policy "Users can insert their own pptx jobs" on public.pptx_jobs for insert to authenticated with check ((user_id = auth.uid()));
create policy "pptx_jobs_select_own" on public.pptx_jobs for select to authenticated using ((user_id = auth.uid()));
create policy "Users can view their own premium usage" on public.premium_usage for select to authenticated, anon using ((auth.uid() = user_id));
create policy "Users can view their own processed orders" on public.processed_orders for select to authenticated, anon using ((auth.uid() = user_id));
create policy "Users can read own profile" on public.profiles for select to authenticated using ((auth.uid() = id));
create policy "Users can update own profile" on public.profiles for update to authenticated using ((auth.uid() = id)) with check ((auth.uid() = id));
create policy "domains_delete_own" on public.project_custom_domains for delete to authenticated, anon using ((auth.uid() = user_id));
create policy "domains_insert_own" on public.project_custom_domains for insert to authenticated, anon with check ((auth.uid() = user_id));
create policy "domains_select_own" on public.project_custom_domains for select to authenticated, anon using ((auth.uid() = user_id));
create policy "domains_update_own" on public.project_custom_domains for update to authenticated, anon using ((auth.uid() = user_id));
create policy "drafts_delete_own" on public.project_drafts for delete to authenticated, anon using ((auth.uid() = user_id));
create policy "drafts_insert_own" on public.project_drafts for insert to authenticated, anon with check ((auth.uid() = user_id));
create policy "drafts_select_own" on public.project_drafts for select to authenticated, anon using ((auth.uid() = user_id));
create policy "drafts_update_own" on public.project_drafts for update to authenticated, anon using ((auth.uid() = user_id));
create policy "versions_insert_owner" on public.project_versions for insert to authenticated, anon with check ((EXISTS ( SELECT 1);
create policy "versions_select_owner" on public.project_versions for select to authenticated, anon using ((EXISTS ( SELECT 1) with check (ects p);
create policy "visits_insert_any" on public.project_visits for insert to anon,authenticated with check ((auth.role() = ANY (ARRAY['anon'::text, 'authenticated'::text])));
create policy "visits_select_owner" on public.project_visits for select to authenticated, anon using ((EXISTS ( SELECT 1) with check (ects p);
create policy "projects_delete_own" on public.projects for delete to authenticated using ((user_id = auth.uid()));
create policy "projects_insert_own" on public.projects for insert to authenticated with check ((user_id = auth.uid()));
create policy "projects_select_own" on public.projects for select to authenticated using ((user_id = auth.uid()));
create policy "projects_update_own" on public.projects for update to authenticated using ((user_id = auth.uid())) with check ((user_id = auth.uid()));
create policy "Users can insert their own promo deadline" on public.promo_deadlines for insert to authenticated, anon with check ((auth.uid() = user_id));
create policy "Users can update their own promo deadline" on public.promo_deadlines for update to authenticated, anon using ((auth.uid() = user_id));
create policy "Users can view their own promo deadline" on public.promo_deadlines for select to authenticated, anon using ((auth.uid() = user_id));
create policy "own push subs" on public.push_subscriptions for all to authenticated using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "Anyone can record a click" on public.referral_clicks for insert to anon,authenticated with check ((auth.role() = ANY (ARRAY['anon'::text, 'authenticated'::text])));
create policy "Referred user marks their conversion" on public.referral_clicks for update to authenticated using (((converted_user_id IS NULL) AND (EXISTS ( SELECT 1) with check (rrals r);
create policy "Referrers view their clicks" on public.referral_clicks for select to authenticated using ((referrer_user_id = auth.uid()));
create policy "Users can insert own referral codes" on public.referral_codes for insert to authenticated with check ((auth.uid() = user_id));
create policy "Users can view own referral codes" on public.referral_codes for select to authenticated using ((auth.uid() = user_id));
create policy "Users create their own referral code" on public.referral_codes for insert to authenticated with check ((user_id = auth.uid()));
create policy "Users view their own referral code" on public.referral_codes for select to authenticated using ((user_id = auth.uid()));
create policy "Users can view own earnings" on public.referral_earnings for select to authenticated using ((auth.uid() = referrer_id));
create policy "Users view their earnings" on public.referral_earnings for select to authenticated using ((referrer_id = auth.uid()));
create policy "Referral tiers are public" on public.referral_tiers for select to anon,authenticated using (true);
create policy "Users can view own referrals" on public.referrals for select to authenticated using ((auth.uid() = referrer_id));
create policy "Users view their referrals" on public.referrals for select to authenticated using (((referrer_id = auth.uid()) OR (referred_id = auth.uid())));
create policy "Users delete own research jobs" on public.research_jobs for delete to authenticated, anon using ((auth.uid() = user_id));
create policy "Users insert own research jobs" on public.research_jobs for insert to authenticated, anon with check ((auth.uid() = user_id));
create policy "Users update own research jobs" on public.research_jobs for update to authenticated, anon using ((auth.uid() = user_id));
create policy "Users view own research jobs" on public.research_jobs for select to authenticated, anon using ((auth.uid() = user_id));
create policy "Users can manage own research messages" on public.research_messages for all to authenticated using ((EXISTS ( SELECT 1) with check (arch_sessions);
create policy "Public can view shared research reports" on public.research_reports for select to anon,authenticated using ((share_token IS NOT NULL));
create policy "Users delete own research reports" on public.research_reports for delete to authenticated, anon using ((auth.uid() = user_id));
create policy "Users insert own research reports" on public.research_reports for insert to authenticated, anon with check ((auth.uid() = user_id));
create policy "Users update own research reports" on public.research_reports for update to authenticated, anon using ((auth.uid() = user_id));
create policy "Users view own research reports" on public.research_reports for select to authenticated, anon using ((auth.uid() = user_id));
create policy "Users can manage own research sessions" on public.research_sessions for all to authenticated using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "Users can view own research sources" on public.research_sources for select to authenticated using ((EXISTS ( SELECT 1) with check (arch_sessions);
create policy "admin read revenue" on public.revenue_ledger for select to authenticated using (has_role(auth.uid(), 'admin'::app_role));
create policy "Anyone can read active reward tasks" on public.reward_tasks for select to authenticated, anon using ((active = true));
create policy "Service role manages reward tasks" on public.reward_tasks for all to authenticated, anon using ((auth.role() = 'service_role'::text)) with check ((auth.role() = 'service_role'::text));
create policy "Users can insert own portal settings" on public.rp_portal_settings for insert to authenticated with check ((auth.uid() = user_id));
create policy "Users can update own portal settings" on public.rp_portal_settings for update to authenticated using ((auth.uid() = user_id));
create policy "Users can view own portal settings" on public.rp_portal_settings for select to authenticated using ((auth.uid() = user_id));
create policy "own scheduled msgs" on public.scheduled_user_messages for all to authenticated using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "findings_owner_all" on public.security_findings for all to authenticated, anon using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "memory_owner_all" on public.security_memory for all to authenticated, anon using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "security_memory_own" on public.security_memory for all to authenticated using ((EXISTS ( SELECT 1) with check (ects p);
create policy "scans_owner_all" on public.security_scans for all to authenticated, anon using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "Public read access for service_incidents" on public.service_incidents for select to authenticated, anon using (true);
create policy "Service role read service_status" on public.service_status for select to service_role using (true);
create policy "Users insert own product reports" on public.shopping_product_reports for insert to authenticated, anon with check ((auth.uid() = user_id));
create policy "Users view own product reports" on public.shopping_product_reports for select to authenticated, anon using ((auth.uid() = user_id));
create policy "Anyone can view showcase items" on public.showcase_items for select to authenticated, anon using (true);
create policy "Users manage own skill files" on public.skill_files for all to authenticated using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "Users manage own skills" on public.skills for all to authenticated using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "Users can manage own slide projects" on public.slide_projects for all to authenticated using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "Anyone can view active slide templates" on public.slide_templates for select to authenticated, anon using ((is_active = true));
create policy "Users can manage own spreadsheet projects" on public.spreadsheet_projects for all to authenticated using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "Users can delete own" on public.status_subscribers for delete to authenticated using ((contact = (( SELECT users.email) with check (.users);
create policy "status_subscribers_delete_own" on public.status_subscribers for delete to authenticated using (((channel = 'email'::text) AND (lower(contact) = lower(COALESCE((auth.jwt() ->> 'email'::text), ''::text)))));
create policy "status_subscribers_insert_own_email" on public.status_subscribers for insert to authenticated with check (((channel = 'email'::text) AND (lower(contact) = lower(COALESCE((auth.jwt() ->> 'email'::text), ''::text)))));
create policy "status_subscribers_select_own" on public.status_subscribers for select to authenticated using (((channel = 'email'::text) AND (lower(contact) = lower(COALESCE((auth.jwt() ->> 'email'::text), ''::text)))));
create policy "Users manage own exams" on public.student_exams for all to authenticated using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "Users manage own mistakes" on public.student_mistakes for all to authenticated using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "Users manage own student profile" on public.student_profiles for all to authenticated using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "Users manage own topics" on public.student_topics for all to authenticated using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "Users manage own study plans" on public.study_plans for all to authenticated using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "Service role manages subscriptions" on public.subscriptions for all to authenticated, anon using (((auth.jwt() ->> 'role'::text) = 'service_role'::text)) with check (((auth.jwt() ->> 'role'::text) = 'service_role'::text));
create policy "Users can view their own subscriptions" on public.subscriptions for select to authenticated, anon using ((auth.uid() = user_id));
create policy "users can view own oauth state" on public.supabase_oauth_states for select to authenticated, anon using ((auth.uid() = user_id));
create policy "Anyone can view active system skills" on public.system_skills for select to anon,authenticated using ((is_active = true));
create policy "Template images are publicly readable" on public.template_images for select to authenticated, anon using (true);
create policy "Anyone can view tool landing images" on public.tool_landing_images for select to anon,authenticated using (true);
create policy "Anyone can view active tool templates" on public.tool_templates for select to anon,authenticated using ((is_active = true));
create policy "TTS voices readable by all authenticated" on public.tts_voices for select to authenticated using (true);
create policy "Users delete own assets" on public.user_assets for delete to authenticated using ((user_id = auth.uid()));
create policy "Users view own assets" on public.user_assets for select to authenticated using ((user_id = auth.uid()));
create policy "Users manage own chat settings" on public.user_chat_settings for all to authenticated using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "ucs_own_delete" on public.user_connector_state for delete to authenticated using ((auth.uid() = user_id));
create policy "ucs_own_insert" on public.user_connector_state for insert to authenticated with check ((auth.uid() = user_id));
create policy "ucs_own_select" on public.user_connector_state for select to authenticated using ((auth.uid() = user_id));
create policy "ucs_own_update" on public.user_connector_state for update to authenticated using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "user_drafts_all_own" on public.user_drafts for all to authenticated using ((user_id = auth.uid())) with check ((user_id = auth.uid()));
create policy "Users can manage own gallery" on public.user_gallery for all to authenticated using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "own delete gh" on public.user_github_connections for delete to authenticated, anon using ((auth.uid() = user_id));
create policy "own select gh" on public.user_github_connections for select to authenticated, anon using ((auth.uid() = user_id));
create policy "users delete own integrations" on public.user_integrations for delete to authenticated using ((user_id = auth.uid()));
create policy "users insert own integrations" on public.user_integrations for insert to authenticated with check ((user_id = auth.uid()));
create policy "users read own integrations" on public.user_integrations for select to authenticated using ((user_id = auth.uid()));
create policy "users update own integrations" on public.user_integrations for update to authenticated using ((user_id = auth.uid())) with check ((user_id = auth.uid()));
create policy "Service inserts KG" on public.user_knowledge_graph for insert to authenticated with check ((auth.uid() = user_id));
create policy "Users delete own KG" on public.user_knowledge_graph for delete to authenticated using ((auth.uid() = user_id));
create policy "Users view own KG" on public.user_knowledge_graph for select to authenticated using ((auth.uid() = user_id));
create policy "memory_delete_own" on public.user_memory_entries for delete to authenticated, anon using ((auth.uid() = user_id));
create policy "memory_insert_own" on public.user_memory_entries for insert to authenticated, anon with check ((auth.uid() = user_id));
create policy "memory_select_own" on public.user_memory_entries for select to authenticated, anon using ((auth.uid() = user_id));
create policy "memory_update_own" on public.user_memory_entries for update to authenticated, anon using ((auth.uid() = user_id));
create policy "Users can insert own memory profile" on public.user_memory_profiles for insert to authenticated with check ((auth.uid() = user_id));
create policy "Users can update own memory profile" on public.user_memory_profiles for update to authenticated using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "Users can view own memory profile" on public.user_memory_profiles for select to authenticated using ((auth.uid() = user_id));
create policy "Users delete their tracks" on public.user_music_tracks for delete to authenticated, anon using ((auth.uid() = user_id));
create policy "Users insert their tracks" on public.user_music_tracks for insert to authenticated, anon with check ((auth.uid() = user_id));
create policy "Users view their tracks" on public.user_music_tracks for select to authenticated, anon using ((auth.uid() = user_id));
create policy "Users delete own payment methods" on public.user_payment_methods for delete to authenticated using ((auth.uid() = user_id));
create policy "Users insert own payment methods" on public.user_payment_methods for insert to authenticated with check (((auth.uid() = user_id) AND (status = 'pending'::text)));
create policy "Users view own payment methods" on public.user_payment_methods for select to authenticated using ((auth.uid() = user_id));
create policy "Users manage own personas" on public.user_personas for all to authenticated, anon using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "user_prefs_insert_own" on public.user_preferences for insert to authenticated with check ((user_id = auth.uid()));
create policy "user_prefs_select_own" on public.user_preferences for select to authenticated using ((user_id = auth.uid()));
create policy "user_prefs_update_own" on public.user_preferences for update to authenticated using ((user_id = auth.uid())) with check ((user_id = auth.uid()));
create policy "Service role manages task progress" on public.user_reward_tasks for all to authenticated, anon using ((auth.role() = 'service_role'::text)) with check ((auth.role() = 'service_role'::text));
create policy "Users insert own task progress" on public.user_reward_tasks for insert to authenticated with check ((auth.uid() = user_id));
create policy "Users read own task progress" on public.user_reward_tasks for select to authenticated using ((auth.uid() = user_id));
create policy "Users update own task progress" on public.user_reward_tasks for update to authenticated using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "admins manage roles" on public.user_roles for all to authenticated using (has_role(auth.uid(), 'admin'::app_role)) with check (has_role(auth.uid(), 'admin'::app_role));
create policy "users read own roles" on public.user_roles for select to authenticated using ((user_id = auth.uid()));
create policy "users can delete own supabase connection" on public.user_supabase_connections for delete to authenticated, anon using ((auth.uid() = user_id));
create policy "users can insert own supabase connection" on public.user_supabase_connections for insert to authenticated, anon with check ((auth.uid() = user_id));
create policy "users can update own supabase connection" on public.user_supabase_connections for update to authenticated, anon using ((auth.uid() = user_id));
create policy "users can view own supabase connection" on public.user_supabase_connections for select to authenticated, anon using ((auth.uid() = user_id));
create policy "fal_video_models_read_anon" on public.video_models for select to anon using ((is_active = true));
create policy "fal_video_models_read_authenticated" on public.video_models for select to authenticated using ((is_active = true));
create policy "Voice templates readable by all authenticated" on public.voice_templates for select to authenticated using (true);
create policy "admin manage ws keys" on public.wavespeed_keys for all to authenticated using (has_role(auth.uid(), 'admin'::app_role)) with check (has_role(auth.uid(), 'admin'::app_role));
create policy "Users can insert own withdrawals" on public.withdrawal_requests for insert to authenticated with check (((auth.uid() = user_id) AND (status = 'pending'::text)));
create policy "Users can view own withdrawals" on public.withdrawal_requests for select to authenticated using ((auth.uid() = user_id));
create policy "Users request their own withdrawals" on public.withdrawal_requests for insert to authenticated with check (((user_id = auth.uid()) AND (status = 'pending'::text)));
create policy "Users view their withdrawals" on public.withdrawal_requests for select to authenticated using ((user_id = auth.uid()));
create policy "members read audit" on public.workspace_audit_log for select to authenticated, anon using (is_workspace_member(workspace_id, auth.uid()));
create policy "admins write brand" on public.workspace_brand_kit for all to authenticated, anon using (is_workspace_admin(workspace_id, auth.uid())) with check (is_workspace_admin(workspace_id, auth.uid()));
create policy "members read brand" on public.workspace_brand_kit for select to authenticated, anon using (is_workspace_member(workspace_id, auth.uid()));
create policy "billing read topups" on public.workspace_credit_topups for select to authenticated, anon using ((is_workspace_admin(workspace_id, auth.uid()) OR (workspace_role_of(workspace_id, auth.uid()) = 'billing_manager'::workspace_role)));
create policy "Invited recipient can view own invite" on public.workspace_invites for select to authenticated, anon using (is_invite_for_current_user(invite_email));
create policy "Owner/admin can manage invites" on public.workspace_invites for all to authenticated, anon using (is_workspace_admin(workspace_id, auth.uid())) with check (is_workspace_admin(workspace_id, auth.uid()));
create policy "admins update requests" on public.workspace_join_requests for update to authenticated, anon using (is_workspace_admin(workspace_id, auth.uid()));
create policy "users create own requests" on public.workspace_join_requests for insert to authenticated, anon with check ((user_id = auth.uid()));
create policy "users see own requests" on public.workspace_join_requests for select to authenticated, anon using (((user_id = auth.uid()) OR is_workspace_admin(workspace_id, auth.uid())));
create policy "admins write status" on public.workspace_member_status for all to authenticated, anon using (is_workspace_admin(workspace_id, auth.uid())) with check (is_workspace_admin(workspace_id, auth.uid()));
create policy "members read status" on public.workspace_member_status for select to authenticated, anon using (is_workspace_member(workspace_id, auth.uid()));
create policy "Members can view co-members" on public.workspace_members for select to authenticated, anon using (is_workspace_member(workspace_id, auth.uid()));
create policy "Owner/admin can add members" on public.workspace_members for insert to authenticated, anon with check ((is_workspace_admin(workspace_id, auth.uid()) OR ((user_id = auth.uid()) AND (EXISTS ( SELECT 1);
create policy "Owner/admin can remove members; member can leave" on public.workspace_members for delete to authenticated, anon using ((is_workspace_admin(workspace_id, auth.uid()) OR (auth.uid() = user_id)));
create policy "Owner/admin can update members" on public.workspace_members for update to authenticated, anon using (is_workspace_admin(workspace_id, auth.uid()));
create policy "own notif prefs" on public.workspace_notification_prefs for all to authenticated, anon using ((user_id = auth.uid())) with check ((user_id = auth.uid()));
create policy "admins write settings" on public.workspace_settings for all to authenticated, anon using (is_workspace_admin(workspace_id, auth.uid())) with check (is_workspace_admin(workspace_id, auth.uid()));
create policy "members read settings" on public.workspace_settings for select to authenticated, anon using (is_workspace_member(workspace_id, auth.uid()));
create policy "Members add shared resources" on public.workspace_shared_resources for insert to authenticated, anon with check ((is_workspace_member(workspace_id, auth.uid()) AND (auth.uid() = shared_by)));
create policy "Members view shared resources" on public.workspace_shared_resources for select to authenticated, anon using (is_workspace_member(workspace_id, auth.uid()));
create policy "Sharer or admin removes shared resource" on public.workspace_shared_resources for delete to authenticated, anon using (((auth.uid() = shared_by) OR is_workspace_admin(workspace_id, auth.uid())));
create policy "Members add task attachments" on public.workspace_task_attachments for insert to authenticated, anon with check (((auth.uid() = uploaded_by) AND (EXISTS ( SELECT 1);
create policy "Members view task attachments" on public.workspace_task_attachments for select to authenticated, anon using ((EXISTS ( SELECT 1) with check (space_tasks t);
create policy "Uploader/admin delete attachments" on public.workspace_task_attachments for delete to authenticated, anon using (((auth.uid() = uploaded_by) OR (EXISTS ( SELECT 1) with check (space_tasks t);
create policy "Author/admin delete comments" on public.workspace_task_comments for delete to authenticated, anon using (((auth.uid() = user_id) OR (EXISTS ( SELECT 1) with check (space_tasks t);
create policy "Members view task comments" on public.workspace_task_comments for select to authenticated, anon using ((EXISTS ( SELECT 1) with check (space_tasks t);
create policy "Members write task comments" on public.workspace_task_comments for insert to authenticated, anon with check (((auth.uid() = user_id) AND (EXISTS ( SELECT 1);
create policy "Creator/admin delete tasks" on public.workspace_tasks for delete to authenticated, anon using ((is_workspace_admin(workspace_id, auth.uid()) OR (auth.uid() = created_by)));
create policy "Creator/assignee/admin update tasks" on public.workspace_tasks for update to authenticated, anon using ((is_workspace_admin(workspace_id, auth.uid()) OR (auth.uid() = created_by) OR (auth.uid() = assignee_id)));
create policy "Members create tasks" on public.workspace_tasks for insert to authenticated, anon with check ((is_workspace_member(workspace_id, auth.uid()) AND (auth.uid() = created_by)));
create policy "Members view tasks" on public.workspace_tasks for select to authenticated, anon using (is_workspace_member(workspace_id, auth.uid()));
create policy "Members insert own usage" on public.workspace_usage for insert to authenticated with check (((auth.uid() = user_id) AND is_workspace_member(workspace_id, auth.uid())));
create policy "Members view own usage" on public.workspace_usage for select to authenticated, anon using (((auth.uid() = user_id) OR is_workspace_admin(workspace_id, auth.uid())));
create policy "Anyone can create a workspace they own" on public.workspaces for insert to authenticated, anon with check ((auth.uid() = owner_id));
create policy "Members can view their workspaces" on public.workspaces for select to authenticated, anon using (is_workspace_member(id, auth.uid()));
create policy "Owner can delete workspace" on public.workspaces for delete to authenticated, anon using ((auth.uid() = owner_id));
create policy "Owner/admin can update workspace" on public.workspaces for update to authenticated, anon using (is_workspace_admin(id, auth.uid()));
create policy "Users can manage own youtube conversations" on public.youtube_conversations for all to authenticated using ((auth.uid() = user_id)) with check ((auth.uid() = user_id));
create policy "Users can manage own youtube messages" on public.youtube_messages for all to authenticated using ((EXISTS ( SELECT 1) with check (ube_conversations);
create policy "Users manage own yt chat messages" on public.yt_video_chat_messages for all to authenticated using ((chat_id IN ( SELECT yt_video_chats.id) with check (ideo_chats);
create policy "Users manage own yt chats" on public.yt_video_chats for all to authenticated using ((user_id = auth.uid())) with check ((user_id = auth.uid()));
